### ISSUE TITLE
Add hookpoint to ValidateAndConfirmPaymentActivity to save payment on success

### ISSUE THREAD

**Issue by charchar** [BroadleafCommerce/BroadleafCommerce#1254] opened 2015-02-04 21:13 UTC
It would be nice to be able to save an OrderPayment as a CustomerPayment after a successful transaction.  Since implementation is dependent on which gateway is used, the default implementation of the hookpoint should do nothing.  Also, should add a transient field on OrderPayment to be used to indicate if it should be saved as a CustomerPayment.

**Comment by phillipuniverse** [comment] 2015-02-04 21:53
@charchar this doesn't work for payments that have already been confirmed right? This only works for payments that are confirmed within that activity?

What if instead you added another workflow activity that did this? Wouldn't it be easier if this was just another activity in the checkout workflow? I think that's how we've solved this in the past.

**Comment by charchar** [comment] 2015-02-04 22:02
@phillipuniverse well, the data in the `PaymentResponseDTO` in `ValidateAndConfirmPaymentActivity` could be leveraged when saving a `CustomerPayment`.  Otherwise we would have to go through the `Order` to get successful payments/transactions, right?

**Comment by charchar** [comment] 2015-02-04 22:19
should probably include @elbertbautista in this

**Comment by elbertbautista** [comment] 2015-02-04 23:22
@charchar - just talked with @phillipuniverse - I forgot that he actually implemented this feature for another client and it seemed like the most universal approach to cover `UNCONFIRMED` and `CONFIRMED` scenarios is to create a placeholder activity after the `ValidateAndConfirmPaymentActivity` instead of that hook I mentioned earlier. Sorry bout that. It looks like you have the right idea, but should probably move the hook to a separate activity. That does entail like you mentioned, that the implementation has to look through the order to get the appropriate entries.

**Comment by charchar** [comment] 2015-02-04 23:36
@elbertbautista Ok, I'll reverse this commit and implement a custom activity.

**Comment by phillipuniverse** [comment] 2015-02-04 23:37
@charchar FYI modifications to workflows are migration-notes worth so mark this with the `requires-migration` label and put a note in the migration docs for 4.0

**Comment by charchar** [comment] 2015-02-04 23:47
@phillipuniverse is this because the ordering of the activities will change?

**Comment by elbertbautista** [comment] 2015-11-20 18:30
Closing - as this will now be rolled into this issue which is tracked here: https://github.com/BroadleafCommerce/QA/issues/1143

**Closed by elbertbautista** 2015-11-20 18:30 UTC
Labels: migration-required, type-enhancement
