### ISSUE TITLE
Issues with static assets intermittently in 3.1.13 GA

### ISSUE THREAD

**Issue by lakshmikalyani** [BroadleafCommerce/BroadleafCommerce#1374] opened 2015-05-27 10:38 UTC
Hi ,
I observed an issue with static assets in broadleaf 3.1.13 GA version. When static assets are accessed from cms or website for few files the following errors are thrown:
java.io.IOException: Unable to delete directory 
java.io.FileNotFoundException: File does not exist (even though file is present in my file system in the proper path)

Upon debugging the issue further I observed that this is happening when brodleaffileservice.closeWorkArea() method is invoked. When its trying to close the directories(directory) or files that got created in the temp folder this issue is triggered. I guess this has something to do with locking system in the files or that particular file is being accessed by another thread. I am not sure about the root cause. But images are not rendered properly because of this issue.

Also can you please let me know the usage of the temporary work area that is getting created. I observed that after creating the file in the temporary directory no operations or actions are performed on this but immediately the work area is closed in the same method(createLocalFileFromInputStream in StaticAssetStorageServiceImpl). I just want to understand the purpose of this

Looking forward for your help on this.Thanks in advance.

**Comment by lakshmikalyani** [comment] 2015-05-29 11:24
Can someone have a look at this please??

**Comment by danielcolgrove** [comment] 2015-05-29 12:10
Yes, we'll take a look and determine what is happening.  Thanks for reporting this.

**Comment by regcole** [comment] 2015-06-09 19:00
@lakshmikalyani We are looking into this. Do you have any steps we can follow to reproduce the behavior you are seeing?

**Comment by lakshmikalyani** [comment] 2015-06-10 06:30
Hi.Thanks for looking into this. I don't have any particular steps. I have upgraded from blc 3.0.12 to 3.1.13 version and started facing this issue.
This issue is triggered only for assets with named operations like resize,width etc where the path of the image is not resolved properly.

**Comment by bpolster** [comment] 2015-06-23 22:40
Just now getting a chance to look at this.    I think the issue is that when we create a temporary directory, we create a multi-level path.    If that path is used by another resources, when we try and cleanup, it should not be considered an error if we are unable to delete our temp directories.  

I'm going to manufacture some scenarios based on this hypothesis and see if I can recreate the problem.

**Comment by bpolster** [comment] 2015-06-23 22:42
@lakshmikalyani - To answer your question, the purpose of our temporary work area is to prevent naming collisions when multiple threads need to do file operations.     Each thread does its file processing in a "work area" and then when finished the completed file or resources is moved to a permanent area.    This is more efficient and easier to manage than trying to prevent multiple threads from performing an IO operation.

**Comment by bpolster** [comment] 2015-06-24 05:40
Closing, tracked at ticket #1452

**Closed by bpolster** 2015-06-24 05:40 UTC

**Comment by lakshmikalyani** [comment] 2015-06-25 05:47
@bpolster ..Hi many thanks for looking into this and for the solution.
