### ISSUE TITLE
SolrException start parameter cannot be negative when loading a Category from the REST API

### ISSUE THREAD

**Issue by brundonsmith** [BroadleafCommerce/BroadleafCommerce#1207] opened 2014-12-28 19:02 UTC
Attempting to retrieve a category (and therefore its products) via the REST API endpoint results in a 500 error, backed by the exception: 
org.apache.solr.common.SolrException: 'start' parameter cannot be negative

This was performed using a valid category ID and the default query string parameters as specified here:
http://www.broadleafcommerce.com/docs/core/current/broadleaf-concepts/rest/rest-endpoints

**Comment by phillipuniverse** [comment] 2015-01-14 22:03
@brundonsmith I assume this was on this endpoint: `/catalog/category/{id}/categories: GET` ?

**Comment by brundonsmith** [comment] 2015-01-14 22:19
I believe it was /catalog/category/{id}: GET

**Comment by phillipuniverse** [comment] 2015-01-15 20:51
Turns out this is a duplicate of #1162. @Jerry77oz put in a fix into DemoSite (meaning, into individual implementations) that involves changing the `@DefaultValue` for the productOffset and subCategoryOffset in to 1 instead of 0. This was referenced in BroadleafCommerce/DemoSite#153.

However, I went and made the Solr query work even if the page passed in was <= 0 so this can be closed for good.

**Closed** 2015-01-15 20:53 UTC
Labels: module-rest, severity-minor, type-bug
