### ISSUE TITLE
Redactor -  WYSIWYG editor is not working properly

### ISSUE THREAD

**Issue by trendchaser4u** [BroadleafCommerce/BroadleafCommerce#2059] opened 2019-02-04 10:17 UTC
Most of the times., if the page has more than one wysiwyg editors the text format options is not working properly. for example if i select text to format Bold, the cursor forced to move beginning of the selected text and `<strong> ` tag added at the beginning of the selected text. 

Please find the attachment

![2](https://user-images.githubusercontent.com/8087340/52202322-315d9c00-2894-11e9-9b50-2e774f5bebd7.PNG)

![1](https://user-images.githubusercontent.com/8087340/52202328-33bff600-2894-11e9-8e01-f67be284fa96.PNG)

**Comment by danielcolgrove** [comment] 2019-02-04 16:07
@trendchaser4u There was a PR submitted and merged that addressed a similar issue.  This was against 5.2.7-GA of Broadleaf (https://github.com/BroadleafCommerce/BroadleafCommerce/pull/1992).  Can you verify the release you are on and whether the changes from this PR is included?

**Comment by trendchaser4u** [comment] 2019-02-06 05:18
@danielcolgrove  The fix is working for a single editor on the page. If the page has more than one editor, there's been an inconsistency on formatting the text.

**Comment by StanislavFedorov** [comment] 2019-10-03 14:27
I am not sure about this fix absolutely, because i could not reproduce it regularly.
Sometimes  this code cancel selection, sometimes not.
For example if we in debug mode it always work properly.
But this bug defenitly happens in this row:
this.$editor.focus();

**Comment by nathandmoore** [comment] 2019-10-25 15:29
Resolved by #2173

**Closed as completed by nathandmoore** 2019-10-25 15:29 UTC
