### ISSUE TITLE
Cart item prices are not updated after a customer login when price is modified in BLC Admin

### ISSUE THREAD

**Issue by vivekjuneja** [BroadleafCommerce/BroadleafCommerce#1206] opened 2014-12-23 05:34 UTC
Hi,

We found an issue with the 3.1.10-GA version of Broadleaf Commerce Framework. We used the 3.1.10-GA version of the DemoSite for this identification. 

The issue summary is : "If some products exist in Cart, and the Admin modifies the pricing for these products from BLC Admin, then the Cart's Total value does NOT Update.

Here are the steps for reproducing this error : 

1. Add 2 products to a Cart from the DemoSite
2. Note the Total shown in the Cart and Close the Cart (using Close Icon at the Corner)
3. Visit Admin and modify the Retail Price of these products
4. Refresh the Product Listing page on the DemoSite to check if the Product's Retail price is updated. 
5. Click on the Cart and check for the SubTotal. The Value is still the Old calculation. The new Retail Price has NOT been accounted for Total Calculation.

![screen shot 2014-12-23 at 2 31 59 pm](https://cloud.githubusercontent.com/assets/122003/5534841/8875e35c-8ab0-11e4-82ad-5428de91c53c.png)

The SubTotal changes if the Update button next to the Product in the cart is clicked. This issue may produce inconsistent results and incorrect user experience for the end customer. 

Let me know if you need more info. 

- Vivek

**Comment by phillipuniverse** [comment] 2015-01-07 06:49
@bpolster one additional comment here: in the current implementation, prices *can* change in the checkout process when pricing shipping. Consider this example:

1. User adds item1 to the cart for $5
2. User goes to checkout
3. Admin changes price of item1 to $8
4. User puts in their shipping address and picks ground shipping
5. Since the order is repriced, the user sees item1 is now $8

Intended behavior? It seemed from your comment that it is not.

**Comment by vivekjuneja** [comment] 2015-01-09 04:13
@bpolster, there seems to be another case which could be related to this : 

1. Admin adds a Sale Price for a Product: $2. Sale Price now is $2. Retail price for the product is $5. 
2. User logs in to the Site. She adds the particular Product (from step 1) to the Cart. Product price and Cart total is $2 
3. Admin removes the Sale Price. Product now retails for $5
4. User logs back to the Site. She sees the particular Product now retails for $5. When she opens the Cart, the Product is still $2. She performs Checkout with $2. 

@phillipuniverse  - The repricing does not happen in the above scenario.

**Comment by bpolster** [comment] 2015-01-09 04:19
Reopen to look at the user logging in and the cart not being repriced in @vivekjuneja prior comment which sounds like a bug.    What @phillipuniverse has described is intended behavior.     A well written system would notify the user that the price changed in this scenario.    I can see the argument that the system would benefit from a mechanism to support modifying shipping (or other late stage cart fees) without issuing a reprice of the items.

**Comment by ktisdell** [comment] 2015-01-19 22:26
@bpolster this seems to be working as designed.  However, based on @vivekjuneja's comments above, I looked into re-pricing the cart after the customer logs in.  It turns out that we already do this.  The problem is that the retail and sale price of the SKU get assigned to the order item when you add to cart, not when pricing occurs.  As a result, they never get reset, even when repricing occurs after a price has changed.  One way around this would be to add a custom activity early in the pricing workflow to iterate over the items and reset the prices from the SKU.  I'm not sure if we want that in the framework, though, as dynamic pricing could get expensive, and others may have different requirements.  Of course, resetting the retail/sale price when there is no dynamic pricing would not be expensive, when is why it may be a better candidate for a custom pricing activity.  Thoughts?

**Comment by bpolster** [comment] 2015-01-19 22:42
Assigned to myself to take a closer look.

**Comment by bpolster** [comment] 2015-01-23 16:48
- [ ] Ensure that updatePrices is called when login brings up a stale cart
- [ ] Provide a method to "repriceCart" that includes a boolean to update SKU prices.   This method would be on OrderService and call "updatePrices" prior to calling the pricing workflow which is responsible for promotions, taxes, shipping, etc.     This hook could be used by implementors who want to reprice the cart via a custom flow.

**Comment by phillipuniverse** [comment] 2015-01-26 08:48
A few things here:

- The assessment from @ktisdell was not right. Individual item prices actually *do* get updated inside of the pricing workflow; it's just obfuscated. Inside [`OfferServiceImpl.applyAndSaveOffersToOrder`](https://github.com/BroadleafCommerce/BroadleafCommerce/blob/193a08d0a9c4855bd2465d3ad66f8fcd1ead05af/core/broadleaf-framework/src/main/java/org/broadleafcommerce/core/offer/service/OfferServiceImpl.java#L288) there is an invocation to `order.updatePrices()`, presumably to ensure that the latest pricing information was up to date before executing offers. Thus, **item prices are actually updated on every execution of the pricing workflow**. You can test this by changing the retail price in the admin after you've already added the item to the cart. If you do anything that executes the pricing workflow the item prices get updated.

- There was a confusing and weird area in `OrderStateAOP` that wraps invocations to `OrderDao.readCartForCustomer`. This was updating item prices for the order but wasn't actually updating the totals. Because of how orders were retrieved, this was happening on every single request. Thus, if you added a cart to your order for $2, then the admin changed it to $5, if you were to view your cart you would see the item cost $5 but the order total cost $2

    - To fix this I removed the ability for this pointcut to update item prices. Item prices should never be updated without correspondingly updating the Order total, which currently only occurs in the pricing workflow

- The case from @vivekjuneja was a still different case. This was less about item prices being updated (because it turns out it technically was) and more about the actual relationship to resetting the sale price from a Sku. In the case he presented, he removed the sale price from the Sku. The `updateSalePrice` method in `DiscreteOrderItem` did not handle this case. It basically had logic that ensured that if you were to ever set the sale price on an order item it never ever got reset if the Sku price changed to `null`

    - To fix this, I added logic in that method to reset the sale price to null on the order item if the price from the Sku was null

I also implemented the 2 items from @bpolster.

@bpolster - it seems that we should actually remove the `order.updatePrices()` from OfferService. Since we have enhanced the `OrderService` to decide whether or not to update item prices, having an obfuscated way that updates item prices deep in the pricing workflow seems wrong. Would you agree?

@vivekjuneja with the changes that I made your bug should be resolved. Also, if you want to explicitly update item prices you can invoke `orderService.save(order, true, true)` which will reprice the items along with everything else in the order.

I did not get a new release built last Friday and I am going to wait until I get another comment here before releasing with these changes, and potentially waiting until I remove that extraneous item pricing call.

**Comment by phillipuniverse** [comment] 2015-01-26 08:57
Just FYI, if I remove the `order.updatePrices` from the `OfferService` then you get kind of a weird result. When I added 'Hoppin Hot Sauce' to the cart the price was $44.99. then I went in the admin and updated it to $84.99. I can update the number of items in my cart (for instance, I have 10 'Hoppin Hot Sauces') and the item price is never updated. In the catalog though, the price is listed as $84.99:

![screen shot 2015-01-26 at 1 54 31 am](https://cloud.githubusercontent.com/assets/684275/5897211/9039307c-a4fe-11e4-858a-ad0642a4e1a6.png)

**Comment by phillipuniverse** [comment] 2015-01-27 05:39
To finally close this out, I am updating the code to such that item prices are **not** refreshed unless that is explicitly what you ask for (via `orderService.save(order, true, true)`. Thus, after an item is added to the cart, that item price will be be the same regardless of what happens with the order (adding items, removing items, pricing anything). Thus, the case that I have the screenshot of above is possible (items in my cart are $44.99 but browsing the catalog they're $84.99).

The only exception to this is when a user logs in and a "stale" order is picked up from the database. When that happens, item prices are refreshed.

Individual implementations might want to customize this and maybe refresh item prices as the first step in checkout.

I am going to resolve this over in #509 where this was originally reported.

**Closed by phillipuniverse** 2015-01-27 05:39 UTC
Labels: difficulty-medium, module-core, needs-information, type-enhancement

**Comment by vivekjuneja** [comment] 2015-01-29 02:49
Thanks @phillipuniverse @ktisdell @bpolster for the help on this.
